### ISSUE TITLE
Subscribe to selectionChange event

### ISSUE THREAD

**Issue by m-s-sh** [fredguile/ng2-md-datatable#3]
If you do <ng2-md-datatable [selectable]="true" (selectionChange)="onSelectionChange($event)">, angular report a error because in that time selectionChange is undefined.

if you move the initialization code  from **ngOnInit** to constructor(**MdDataTableComponent**), it is working.
```javascript
ngOnInit() {
    this.selectionChange = new EventEmitter<IDatatableSelectionEvent>(true); // async
    this.sortChange = new EventEmitter<IDatatableSortEvent>(true); // async
```
Or may be I am wrong?

**Comment by fredguile** [comment]
Good finding, that is most probably right. I'll fix this in next release!
