### ISSUE TITLE
pagination not limiting the number of items on the page

### ISSUE THREAD

**Issue by grimace** [fredguile/ng2-md-datatable#43]
pagination element is showing up, My rows have 100 items and they are all showing, itemsPerPage is set to 20.  I'm wondering if I'm missing something about connecting the pagination element up.  What could I be missing?

```<ng2-md-datatable selectable id="assetDatatable">
  <ng2-md-datatable-header>
    <ng2-md-datatable-column sortableValue="name">Name</ng2-md-datatable-column>
    <ng2-md-datatable-column sortableValue="size" numeric>Size</ng2-md-datatable-column>
    <ng2-md-datatable-column sortableValue="duration" numeric>Duration</ng2-md-datatable-column>
    <ng2-md-datatable-column sortableValue="filename">File Name</ng2-md-datatable-column>
    <ng2-md-datatable-column sortableValue="updatedAt" date>Last Modified</ng2-md-datatable-column>
    <ng2-md-datatable-column sortableValue="path">Path</ng2-md-datatable-column>
    <ng2-md-datatable-column sortableValue="assetType">Asset Type</ng2-md-datatable-column>
  </ng2-md-datatable-header>
  <tbody>
    <ng2-md-datatable-row *ngFor="let row of rows" selectableValue="name">
      <td>{{row.name}}</td>
      <td class="numeric">{{row.size}}</td>
      <td class="numeric">{{row.duration}}</td>
      <td>{{row.filename}}</td>
      <td class="date">{{row.updatedAt}}</td>
      <td>{{row.path}}</td>
      <td>{{row.assetType}}</td>
    </ng2-md-datatable-row>
  </tbody>
</ng2-md-datatable>

<ng2-md-datatable-pagination id="pagination"
  [currentPage]="currentPage"
  [itemsPerPage]="itemsPerPage"
  [itemsCount]="itemsCount"
  [itemsPerPageChoices]="itemsPerPageChoices"
  [itemsPerPageFirstChoice]="itemsPerPageFirstChoice"
  >
</ng2-md-datatable-pagination>
```

**Comment by fredguile** [comment]
Hi, I admit that it's a bit confusing (and would deserve a bit more documentation...), but the pagination is actually really dumb and doesn't alter the datasource, nor the datatable (*ngFor="let row of rows" runs with your 100 items). You could think of this component as a simple pagination "calculator". 

To complete pagination, you basically need two things:
1. add a page and limit parameters to the service that provides your datasource, so as to return a slice of the whole data. 

For instance here:
https://github.com/fredguile/ng2-md-datatable/blob/master/src/demo-app/src/app/app.service.ts

Of course this implementation is really minimalistic: `demoDatasource.slice(offset, offset + limit);`
In real use cases, you would pass them to an API call that would return paginated data.

2. listen to the pagination component events to call your service with updated pagination parameters. For instance (using an Observable wrapping the eventEmitter):

```
Observable.from(this.pagination.paginationChange)
.takeUntil(this.unmount$)
.subscribe((e: IDatatablePaginationEvent) => this.fetchDemoDataSource(e.page, e.itemsPerPage));
```

I know that there are datatables that do everything for you based on configuration & conventions, this one is more "modular", let's say ;)

**Comment by grimace** [comment]
Ok, I see now.  Can't seem to get the paginationChange event to fire, though and only the onClickFIrst() is clickable.  Can I override those pagination functions?

**Comment by grimace** [comment]
NM, I wasn't setting the totalCount.  Working now. Thx
