### ISSUE TITLE
index"' has no exported member 'InjectionToken'

### ISSUE THREAD

**Issue by MorlaRamakrishna** [fredguile/ng2-md-datatable#45]
In my Angular 2 Getting **index"' has no exported member 'InjectionToken'** error after module import

**Comment by fredguile** [comment]
That was introduced in Angular 4.x. You can use up to v1.2.x of this lib with Angular 2.x, after that you need to update to Angular 4.x (I strongly recommend, shall not be difficult).

**Comment by jj-julia** [comment]
and if you can't upgrade to angular 4. How does one deal with the issue above?

**Comment by fredguile** [comment]
Then we should find a good soul to port all improvements made on versions 1.3.x to the 1.2.x branch ;)
