### ISSUE TITLE
IE 11 problem with sorting table

### ISSUE THREAD

**Issue by numsu** [fredguile/ng2-md-datatable#46]
Hi!

I'm using the module with sortable columns. Everything works perfectly on all other browsers except for IE.

The error I'm getting in the console is:
`ERROR TypeError: Object doesn't support property or method 'includes'`
`ERROR CONTEXT [object Object]`

I have imported the polyfill for `String.includes` in my app.

Sorting works just fine, but the sort arrow or bolding does not appear.

**Comment by fredguile** [comment]
I'd say that's not linked to the lib itself, but more to your client app that shall packages specific IE11 (maybe look into Angular-CLI issues?). I'm currently working on a similar problem on another project done with React & Babel, and it seems tricky to have polyfills correctly loaded before the main code.

I suppose you did enable them here?
https://github.com/fredguile/ng2-md-datatable/blob/master/src/demo-app/src/polyfills.ts

**Comment by numsu** [comment]
Yes, I've enabled them right there (on the main project) and Angular CLI compiles the project.

**Comment by fredguile** [comment]
I'll test and let you kow if I find a solution.

**Comment by fredguile** [comment]
Have a look at my last commit:
https://github.com/fredguile/ng2-md-datatable/commit/64e8c8815f424adf25799ee00255f38c6bedf110

Array.includes gets apparently polyfilled by `import 'core-js/es7/array';`
