### ISSUE TITLE
Thank you for this project

### ISSUE THREAD

**Issue by leonardseymore** [fredguile/ng2-md-datatable#7]
Thank you for this project! Please keep up the good work, it's a lifesaver

**Comment by fredguile** [comment]
You're very welcome!

I was away for 2 weeks as I received all this supportive feedback ;) There was even a PR from @TitanNano that redesigned the pagination component in a very neat way!

![screen shot 2017-03-21 at 16 55 42](https://cloud.githubusercontent.com/assets/209813/24156601/418f4244-0e57-11e7-955c-a36713464f1f.png)

Thanks you all for making that datatable even stronger. Expect a release soon with these changes!
